import { Shop } from '@/domain/shop/shop.model'
import { Product } from '@/domain/product/product.model'

export const SEED_SHOPS: Shop[] = [
  {
    id: 'shop-001',
    shopNumber: 1,
    name: 'ร้านก๋วยเตี๋ยวแม่ศรี',
    description: 'ก๋วยเตี๋ยวต้มยำโบราณสูตรเตาถ่าน น้ำซุปเข้มข้น มะนาวแท้ เครื่องแน่น',
    imageUrl: '/images/stalls/noodle.webp',
    coverUrl: '/images/stalls/noodle.webp',
    category: 'noodle',
    zone: 'ร้านที่ 1',
    isOpen: true,
    rating: 4.9,
    reviewCount: 342,
    preparationTime: 12,
    tags: ['ก๋วยเตี๋ยว', 'ต้มยำ', 'รสเด็ด'],
    menuCategories: [
      { id: 'cat-001-1', name: 'ก๋วยเตี๋ยว', shopId: 'shop-001' },
      { id: 'cat-001-2', name: 'ของทานเล่น', shopId: 'shop-001' },
    ],
  },
  {
    id: 'shop-002',
    shopNumber: 2,
    name: 'กะเพรากระทะร้อนริมชล',
    description: 'กะเพราพริกแห้งโบราณ หมูกรอบคั่วพริกเกลือ หอมกลิ่นกระทะร้อน',
    imageUrl: '/images/stalls/krapal.webp',
    coverUrl: '/images/stalls/krapal.webp',
    category: 'rice',
    zone: 'ร้านที่ 2',
    isOpen: true,
    rating: 4.9,
    reviewCount: 418,
    preparationTime: 10,
    tags: ['กะเพรา', 'หมูกรอบ', 'กระทะร้อน'],
    menuCategories: [
      { id: 'cat-002-1', name: 'เมนูกะเพรา', shopId: 'shop-002' },
      { id: 'cat-002-2', name: 'เมนูคั่วพริกเกลือ', shopId: 'shop-002' },
    ],
  },
  {
    id: 'shop-003',
    shopNumber: 3,
    name: 'ผัดไทยกุ้งสดริมน้ำ',
    description: 'ผัดไทยกุ้งสดไข่ห่อสูตรโบราณ ซอสมะขามเข้มข้น หอยทอดกะทะร้อนกรอบนอกนุ่มใน',
    imageUrl: '/images/stalls/padthai.webp',
    coverUrl: '/images/stalls/padthai.webp',
    category: 'thai',
    zone: 'ร้านที่ 3',
    isOpen: true,
    rating: 4.8,
    reviewCount: 278,
    preparationTime: 10,
    tags: ['ผัดไทย', 'กุ้งสด', 'หอยทอด'],
    menuCategories: [
      { id: 'cat-003-1', name: 'ผัดไทย', shopId: 'shop-003' },
      { id: 'cat-003-2', name: 'หอยทอดกระทะร้อน', shopId: 'shop-003' },
    ],
  },
  {
    id: 'shop-004',
    shopNumber: 4,
    name: 'ซีฟู้ด & ทะเลเผาริมชล',
    description: 'กุ้งแม่น้ำเผาสดๆ น้ำจิ้มซีฟู้ดมะนาวแท้ ข้าวผัดต้มยำทะเลเครื่องล้น',
    imageUrl: '/images/stalls/seafood.webp',
    coverUrl: '/images/stalls/seafood.webp',
    category: 'seafood',
    zone: 'ร้านที่ 4',
    isOpen: true,
    rating: 4.8,
    reviewCount: 312,
    preparationTime: 15,
    tags: ['ซีฟู้ด', 'กุ้งเผา', 'ทะเล'],
    menuCategories: [
      { id: 'cat-004-1', name: 'ทะเลเผา', shopId: 'shop-004' },
      { id: 'cat-004-2', name: 'อาหารจานเดียว', shopId: 'shop-004' },
    ],
  },
  {
    id: 'shop-005',
    shopNumber: 5,
    name: 'ซูชิคำโตริมชล',
    description: 'แซลมอนซาชิมิสดฉ่ำ ซูชิคำโต ข้าวหน้าแซลมอนดองซีอิ๊วเกาหลี',
    imageUrl: '/images/stalls/sushi.webp',
    coverUrl: '/images/stalls/sushi.webp',
    category: 'international',
    zone: 'ร้านที่ 5',
    isOpen: true,
    rating: 4.7,
    reviewCount: 245,
    preparationTime: 8,
    tags: ['ซูชิ', 'แซลมอน', 'อาหารญี่ปุ่น'],
    menuCategories: [
      { id: 'cat-005-1', name: 'ซูชิ & ซาชิมิ', shopId: 'shop-005' },
      { id: 'cat-005-2', name: 'ข้าวหน้าดงบุริ', shopId: 'shop-005' },
    ],
  },
  {
    id: 'shop-006',
    shopNumber: 6,
    name: 'พิซซ่าเตาฟืนริมชล',
    description: 'พิซซ่าแป้งบางกรอบอบเตาฟืน ชีสเยิ้มๆ สปาเก็ตตี้คาโบนาร่าทรัฟเฟิล',
    imageUrl: '/images/stalls/pizza.webp',
    coverUrl: '/images/stalls/pizza.webp',
    category: 'international',
    zone: 'ร้านที่ 6',
    isOpen: true,
    rating: 4.8,
    reviewCount: 196,
    preparationTime: 15,
    tags: ['พิซซ่า', 'เตาฟืน', 'สปาเก็ตตี้'],
    menuCategories: [
      { id: 'cat-006-1', name: 'พิซซ่าเตาฟืน', shopId: 'shop-006' },
      { id: 'cat-006-2', name: 'พาสต้า & ทานเล่น', shopId: 'shop-006' },
    ],
  },
  {
    id: 'shop-007',
    shopNumber: 7,
    name: 'คาเฟ่เค้ก & เบเกอรี่ริมชล',
    description: 'เค้กมะพร้าวอ่อนใบเตยสด เค้กส้มหน้านิ่ม ครัวซองต์เนยสด ชาไทยฟองนุ่ม',
    imageUrl: '/images/stalls/cake.webp',
    coverUrl: '/images/stalls/cake.webp',
    category: 'dessert',
    zone: 'ร้านที่ 7',
    isOpen: true,
    rating: 4.9,
    reviewCount: 388,
    preparationTime: 5,
    tags: ['เค้ก', 'เบเกอรี่', 'เครื่องดื่ม'],
    menuCategories: [
      { id: 'cat-007-1', name: 'เค้ก & เบเกอรี่', shopId: 'shop-007' },
      { id: 'cat-007-2', name: 'เครื่องดื่ม', shopId: 'shop-007' },
    ],
  },
]

export const SEED_PRODUCTS: Product[] = [
  // ── shop-001 ร้านก๋วยเตี๋ยวแม่ศรี ──────────────────────────────────
  {
    id: 'prod-001',
    shopId: 'shop-001',
    categoryId: 'cat-001-1',
    name: 'ก๋วยเตี๋ยวต้มยำโบราณ',
    description: 'ก๋วยเตี๋ยวต้มยำมะนาวแท้ หมูสับ ลูกชิ้น ถั่วคั่วหอมสดใหม่',
    price: 55,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-001',
        name: 'ชนิดเส้น',
        required: true,
        maxSelect: 1,
        choices: [
          { id: 'ch-001', name: 'เส้นเล็ก', priceAdd: 0 },
          { id: 'ch-002', name: 'เส้นใหญ่', priceAdd: 0 },
          { id: 'ch-003', name: 'บะหมี่เหลือง', priceAdd: 0 },
          { id: 'ch-004', name: 'วุ้นเส้น', priceAdd: 5 },
        ],
      },
    ],
    tags: ['bestseller'],
  },
  {
    id: 'prod-002',
    shopId: 'shop-001',
    categoryId: 'cat-001-1',
    name: 'ก๋วยเตี๋ยวเรือหมูตุ๋นน้ำตก',
    description: 'ก๋วยเตี๋ยวน้ำตกหมูตุ๋นยาจีน น้ำซุปเข้มข้น เครื่องแน่นเต็มชาม',
    price: 60,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-002',
        name: 'ชนิดเส้น',
        required: true,
        maxSelect: 1,
        choices: [
          { id: 'ch-005', name: 'เส้นเล็ก', priceAdd: 0 },
          { id: 'ch-006', name: 'เส้นหมี่', priceAdd: 0 },
          { id: 'ch-007', name: 'เส้นใหญ่', priceAdd: 0 },
        ],
      },
    ],
    tags: ['popular'],
  },
  {
    id: 'prod-003',
    shopId: 'shop-001',
    categoryId: 'cat-001-2',
    name: 'เกี๊ยวกรอบต้มยำทรงเครื่อง',
    description: 'เกี๊ยวทอดกรอบเสิร์ฟพร้อมน้ำยำรสจัดจ้านและหมูสับ',
    price: 40,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: 50,
    options: [],
    tags: [],
  },

  // ── shop-002 กะเพรากระทะร้อนริมชล ───────────────────────────────
  {
    id: 'prod-004',
    shopId: 'shop-002',
    categoryId: 'cat-002-1',
    name: 'ข้าวกะเพราหมูกรอบกระทะร้อน',
    description: 'หมูกรอบแท้คั่วกะเพราพริกแห้งโบราณ หอมกลิ่นกระทะร้อนรสเข้มข้น',
    price: 65,
    imageUrl: '/images/food/rice.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-003',
        name: 'เพิ่มไข่',
        required: false,
        maxSelect: 1,
        choices: [
          { id: 'ch-008', name: 'ไข่ดาวกรอบ', priceAdd: 10 },
          { id: 'ch-009', name: 'ไข่ข้นนุ่ม', priceAdd: 15 },
        ],
      },
    ],
    tags: ['bestseller'],
  },
  {
    id: 'prod-005',
    shopId: 'shop-002',
    categoryId: 'cat-002-1',
    name: 'ข้าวกะเพราเนื้อโคขุนสับ',
    description: 'เนื้อโคขุนคัดพิเศษ ผัดกะเพราพริกแห้งรสจัดจ้านเข้าเนื้อ',
    price: 75,
    imageUrl: '/images/food/rice.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-004',
        name: 'เพิ่มไข่',
        required: false,
        maxSelect: 1,
        choices: [
          { id: 'ch-010', name: 'ไข่ดาวกรอบ', priceAdd: 10 },
          { id: 'ch-011', name: 'ไข่ข้นนุ่ม', priceAdd: 15 },
        ],
      },
    ],
    tags: ['popular'],
  },
  {
    id: 'prod-006',
    shopId: 'shop-002',
    categoryId: 'cat-002-2',
    name: 'ข้าวหมูกรอบคั่วพริกเกลือ',
    description: 'หมูกรอบหั่นชิ้นโตคั่วกระเทียมพริกเกลือหอมกรอบ ราดข้าวสวยร้อนๆ',
    price: 65,
    imageUrl: '/images/food/rice.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: [],
  },

  // ── shop-003 ผัดไทยกุ้งสดริมน้ำ ──────────────────────────────────
  {
    id: 'prod-007',
    shopId: 'shop-003',
    categoryId: 'cat-003-1',
    name: 'ผัดไทยกุ้งสดไข่ห่อ',
    description: 'ผัดไทยกุ้งสดตัวโตห่อไข่สูตรโบราณ ซอสมะขามเปียกเข้มข้นเหนียวนุ่ม',
    price: 70,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-005',
        name: 'ท็อปปิ้งพิเศษ',
        required: false,
        maxSelect: 1,
        choices: [
          { id: 'ch-012', name: 'กุ้งเพิ่ม (2 ตัว)', priceAdd: 25 },
          { id: 'ch-013', name: 'แคบหมูกรอบ', priceAdd: 15 },
        ],
      },
    ],
    tags: ['bestseller'],
  },
  {
    id: 'prod-008',
    shopId: 'shop-003',
    categoryId: 'cat-003-2',
    name: 'หอยทอดกะทะร้อนกรอบนอกนุ่มใน',
    description: 'หอยแมลงภู่สดคลุกแป้งสูตรลับ ทอดกระทะร้อนกรอบฟู เสิร์ฟพร้อมน้ำจิ้มรสเด็ด',
    price: 60,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: ['popular'],
  },
  {
    id: 'prod-009',
    shopId: 'shop-003',
    categoryId: 'cat-003-1',
    name: 'ผัดไทยหมูนุ่มโบราณ',
    description: 'ผัดไทยหมูนุ่มหมักซอส เส้นจันทน์เหนียวนุ่ม ใส่ถั่วงอกและใบกุยช่ายสด',
    price: 55,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: [],
  },

  // ── shop-004 ซีฟู้ด & ทะเลเผาริมชล ──────────────────────────────
  {
    id: 'prod-010',
    shopId: 'shop-004',
    categoryId: 'cat-004-1',
    name: 'กุ้งแม่น้ำเผาผ่าหลัง (3 ตัว)',
    description: 'กุ้งแม่น้ำสดๆ ผ่าหลังมันเยิ้ม ย่างเตาถ่านหอมกรุ่น เสิร์ฟคู่น้ำจิ้มซีฟู้ดมะนาวแท้',
    price: 140,
    imageUrl: '/images/food/isaan.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-006',
        name: 'สูตรน้ำจิ้ม',
        required: true,
        maxSelect: 1,
        choices: [
          { id: 'ch-014', name: 'ซีฟู้ดมะนาวสดแท้ (เปรี้ยวเผ็ด)', priceAdd: 0 },
          { id: 'ch-015', name: 'ซีฟู้ดพริกแดงจัดจ้าน', priceAdd: 0 },
        ],
      },
    ],
    tags: ['bestseller'],
  },
  {
    id: 'prod-011',
    shopId: 'shop-004',
    categoryId: 'cat-004-2',
    name: 'ข้าวผัดต้มยำทะเลกระทะร้อน',
    description: 'ข้าวสวยผัดเครื่องต้มยำหอมกรุ่น กุ้ง หมึก หอยแมลงภู่สดแน่นจาน',
    price: 75,
    imageUrl: '/images/food/rice.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: ['popular'],
  },
  {
    id: 'prod-012',
    shopId: 'shop-004',
    categoryId: 'cat-004-1',
    name: 'หมึกไข่นึ่งมะนาวราดแซ่บ',
    description: 'หมึกสดแน่นไข่เต็มท้อง นึ่งมะนาวสดพริกขี้หนูสวนรสจัดจ้านถึงใจ',
    price: 85,
    imageUrl: '/images/food/isaan.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: [],
  },

  // ── shop-005 ซูชิคำโตริมชล ─────────────────────────────────────
  {
    id: 'prod-013',
    shopId: 'shop-005',
    categoryId: 'cat-005-1',
    name: 'เซ็ตซูชิรวมยอดฮิต 10 คำ',
    description: 'แซลมอน ทูน่า กุ้งหวาน ไข่หวาน ยำสาหร่าย และปูอัด ปั้นสดคำโต',
    price: 99,
    imageUrl: '/images/food/isaan.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-007',
        name: 'วาซาบิ',
        required: true,
        maxSelect: 1,
        choices: [
          { id: 'ch-016', name: 'แยกวาซาบิ', priceAdd: 0 },
          { id: 'ch-017', name: 'ป้ายวาซาบิในคำเลย', priceAdd: 0 },
        ],
      },
    ],
    tags: ['bestseller'],
  },
  {
    id: 'prod-014',
    shopId: 'shop-005',
    categoryId: 'cat-005-1',
    name: 'แซลมอนซาชิมิสดฉ่ำ (6 ชิ้น)',
    description: 'ปลาแซลมอนนอร์เวย์แล่สด เนื้อหวานลายสวย เสิร์ฟพร้อมโชยุและวาซาบิสด',
    price: 89,
    imageUrl: '/images/food/isaan.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: ['popular'],
  },
  {
    id: 'prod-015',
    shopId: 'shop-005',
    categoryId: 'cat-005-2',
    name: 'ข้าวหน้าแซลมอนดองซีอิ๊วเกาหลี',
    description: 'แซลมอนดองซีอิ๊วสูตรกลมกล่อม ท็อปไข่ดองและงาคั่ว เสิร์ฟพร้อมสาหร่ายแผ่น',
    price: 85,
    imageUrl: '/images/food/rice.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: [],
  },

  // ── shop-006 พิซซ่าเตาฟืนริมชล ─────────────────────────────────
  {
    id: 'prod-016',
    shopId: 'shop-006',
    categoryId: 'cat-006-1',
    name: 'พิซซ่าเตาฟืนฮาวายเอี้ยนชีสล้น',
    description: 'แป้งพิซซ่าโฮมเมดบางกรอบอบเตาฟืน แฮม สับปะรดฉ่ำ และมอสซาเรลล่าชีสยืด',
    price: 129,
    imageUrl: '/images/food/rice.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-008',
        name: 'เพิ่มชีส',
        required: false,
        maxSelect: 1,
        choices: [
          { id: 'ch-018', name: 'เพิ่มมอสซาเรลล่าชีสพิเศษ', priceAdd: 25 },
        ],
      },
    ],
    tags: ['bestseller'],
  },
  {
    id: 'prod-017',
    shopId: 'shop-006',
    categoryId: 'cat-006-2',
    name: 'สปาเก็ตตี้คาโบนาร่าทรัฟเฟิล',
    description: 'เส้นสปาเก็ตตี้เหนียวนุ่ม ผัดครีมซอสไข่แดง เบคอนกรอบ และกลิ่นหอมทรัฟเฟิล',
    price: 89,
    imageUrl: '/images/food/noodle.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: ['popular'],
  },
  {
    id: 'prod-018',
    shopId: 'shop-006',
    categoryId: 'cat-006-2',
    name: 'ขนมปังกระเทียมชีสกรอบ',
    description: 'ขนมปังฝรั่งเศสทาเนยกระเทียมโรยพาร์เมซานชีส อบกรอบนอกนุ่มใน',
    price: 49,
    imageUrl: '/images/food/dessert.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: [],
  },

  // ── shop-007 คาเฟ่เค้ก & เบเกอรี่ริมชล ──────────────────────────
  {
    id: 'prod-019',
    shopId: 'shop-007',
    categoryId: 'cat-007-1',
    name: 'เค้กมะพร้าวอ่อนใบเตยสด',
    description: 'เนื้อเค้กชิฟฟ่อนใบเตยหอมนุ่ม สอดไส้ซอสมะพร้าวอ่อนครีมสดรสละมุน',
    price: 65,
    imageUrl: '/images/food/dessert.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: ['bestseller'],
  },
  {
    id: 'prod-020',
    shopId: 'shop-007',
    categoryId: 'cat-007-1',
    name: 'เค้กส้มหน้านิ่มเนื้อสปันจ์',
    description: 'เค้กสปันจ์นุ่มเบา ราดซอสส้มแมนดารินรสเปรี้ยวอมหวานสดชื่น',
    price: 55,
    imageUrl: '/images/food/dessert.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: ['popular'],
  },
  {
    id: 'prod-021',
    shopId: 'shop-007',
    categoryId: 'cat-007-1',
    name: 'ครัวซองต์เนยสดฝรั่งเศสอบร้อน',
    description: 'ครัวซองต์แป้งพัฟฟ์กรอบนอกนุ่มใน ฉ่ำเนยสดแท้จากฝรั่งเศส',
    price: 45,
    imageUrl: '/images/food/dessert.jpg',
    isAvailable: true,
    stock: null,
    options: [],
    tags: [],
  },
  {
    id: 'prod-022',
    shopId: 'shop-007',
    categoryId: 'cat-007-2',
    name: 'ชาไทยเย็นฟองนมนุ่ม',
    description: 'ชาไทยเบลนด์เข้มข้น หวานมันกลมกล่อม ท็อปฟองนมนุ่มละมุนลิ้น',
    price: 40,
    imageUrl: '/images/food/drink.jpg',
    isAvailable: true,
    stock: null,
    options: [
      {
        id: 'opt-009',
        name: 'ระดับความหวาน',
        required: false,
        maxSelect: 1,
        choices: [
          { id: 'ch-019', name: 'หวานน้อย 50%', priceAdd: 0 },
          { id: 'ch-020', name: 'หวานปกติ 100%', priceAdd: 0 },
          { id: 'ch-021', name: 'ไม่หวาน 0%', priceAdd: 0 },
        ],
      },
    ],
    tags: ['popular'],
  },
]
